//All action types are defined and exported from heres

export const GET_USER_CITY_START = 'GET_USER_CITY_START';
export const GET_USER_CITY_SUCCESS = 'GET_USER_CITY_SUCCESS';
export const GET_USER_CITY_FAIL = 'GET_USER_CITY_FAIL';

export const SEARCH_CITY_COORD_START = 'SEARCH_CITY_COORD_START';
export const SEARCH_CITY_COORD_SUCCESS = 'SEARCH_CITY_COORD_SUCCESS';
export const SEARCH_CITY_COORD_FAIL = 'SEARCH_CITY_COORD_FAIL';

export const SEARCH_CITY_START = 'SEARCH_CITY_START';
export const SEARCH_CITY_SUCCESS = 'SEARCH_CITY_SUCCESS';
export const SEARCH_CITY_FAIL = 'SEARCH_CITY_FAIL';

export const ON_DAY_SELECTION = 'ON_DAY_SELECTION';
